test change dockerfile

diff --git a/Backend/Product/Dockerfile b/Backend/Product/Dockerfile
--- a/Backend/Product/Dockerfile
+++ b/Backend/Product/Dockerfile
@@ -1,26 +1,91 @@
-FROM php:7.3-cli
+# FROM php:7.3-cli
 
-# Install package dependencies
-RUN apt update && apt install -y libmagickwand-dev git libzip-dev unzip
+# # Install package dependencies
+# RUN apt update && apt install -y libmagickwand-dev git libzip-dev unzip
 
-# Enable default PHP extensions
-RUN docker-php-ext-install mysqli pdo_mysql pcntl bcmath zip soap intl gd exif
+# # Enable default PHP extensions
+# RUN docker-php-ext-install mysqli pdo_mysql pcntl bcmath zip soap intl gd exif
 
-# Add imagick from pecl
-RUN pecl install imagick && echo 'extension=imagick.so' >> /usr/local/etc/php/php.ini
+# # Add imagick from pecl
+# RUN pecl install imagick && echo 'extension=imagick.so' >> /usr/local/etc/php/php.ini
 
-# Install nodejs & yarn
-RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
-    && DEBIAN_FRONTEND=noninteractive apt-get install nodejs -yqq \
-    && npm i -g npm \
-    && curl -o- -L https://yarnpkg.com/install.sh | bash \
-    && npm cache clean --force
+# # Install nodejs & yarn
+# RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
+#     && DEBIAN_FRONTEND=noninteractive apt-get install nodejs -yqq \
+#     && npm i -g npm \
+#     && curl -o- -L https://yarnpkg.com/install.sh | bash \
+#     && npm cache clean --force
 
-# Install composer
-ENV COMPOSER_HOME=/composer
-ENV PATH=./vendor/bin:/composer/vendor/bin:/root/.yarn/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-ENV COMPOSER_ALLOW_SUPERUSER=1
-RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
+# # Install composer
+# ENV COMPOSER_HOME=/composer
+# ENV PATH=./vendor/bin:/composer/vendor/bin:/root/.yarn/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+# ENV COMPOSER_ALLOW_SUPERUSER=1
+# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
 
-WORKDIR /var/www
-# https://ma.ttias.be/a-github-ci-workflow-tailored-to-laravel-applications/
+# WORKDIR /var/www
+# # https://ma.ttias.be/a-github-ci-workflow-tailored-to-laravel-applications/
+
+FROM php:7-alpine
+
+RUN set -eux; \
+  apk add --no-cache --virtual .composer-rundeps \
+    bash \
+    coreutils \
+    git \
+    make \
+    mercurial \
+    openssh-client \
+    patch \
+    subversion \
+    tini \
+    unzip \
+    zip
+
+RUN set -eux; \
+  apk add --no-cache --virtual .build-deps \
+    libzip-dev \
+    zlib-dev \
+  ; \
+  docker-php-ext-install -j "$(nproc)" \
+    zip \
+  ; \
+  runDeps="$( \
+    scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
+      | tr ',' '\n' \
+      | sort -u \
+      | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
+    )"; \
+  apk add --no-cache --virtual .composer-phpext-rundeps $runDeps; \
+  apk del .build-deps
+
+RUN printf "# composer php cli ini settings\n\
+date.timezone=UTC\n\
+memory_limit=-1\n\
+" > $PHP_INI_DIR/php-cli.ini
+
+ENV COMPOSER_ALLOW_SUPERUSER 1
+ENV COMPOSER_HOME /tmp
+ENV COMPOSER_VERSION 2.0.0-alpha1
+
+RUN set -eux; \
+  curl --silent --fail --location --retry 3 --output /tmp/installer.php --url https://raw.githubusercontent.com/composer/getcomposer.org/cb19f2aa3aeaa2006c0cd69a7ef011eb31463067/web/installer; \
+  php -r " \
+    \$signature = '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5'; \
+    \$hash = hash('sha384', file_get_contents('/tmp/installer.php')); \
+    if (!hash_equals(\$signature, \$hash)) { \
+      unlink('/tmp/installer.php'); \
+      echo 'Integrity check failed, installer is either corrupt or worse.' . PHP_EOL; \
+      exit(1); \
+    }"; \
+  php /tmp/installer.php --no-ansi --install-dir=/usr/bin --filename=composer --version=${COMPOSER_VERSION}; \
+  composer --ansi --version --no-interaction; \
+  rm -f /tmp/installer.php; \
+  find /tmp -type d -exec chmod -v 1777 {} +
+
+COPY docker-entrypoint.sh /docker-entrypoint.sh
+
+WORKDIR /app
+
+ENTRYPOINT ["/docker-entrypoint.sh"]
+
+CMD ["composer"]
